#+OPTIONS: num:nil ^:nil toc:nil author:nil

* Working

* Backlog
** someday Does it make sense to move base image from Ubuntu to k3os?

* Done
** done What about a test to make sure ctrlplane is not running a k3s agent/kubelet?
   SCHEDULED: <2019-07-22 Mon>
** done What's the resolution for Consul via Helm as **dedicated** Vault storage?
   DEADLINE: <2019-07-24 Wed> SCHEDULED: <2019-07-22 Mon>
** done [#A] Why are workers not getting an update node-token?
   DEADLINE: <2019-07-22 Mon>
** done [#A] read and modify the Consul values
*** done spread amongst AZs
    DEADLINE: <2019-08-01 Thu>
** done [#B] non-labelled nodes are still getting Consul client
   DEADLINE: <2019-08-02 Fri>
** done [#C] testing of the Consul af/anti-af logic
  DEADLINE: <2019-07-23 Tue> SCHEDULED: <2019-07-22 Mon>

** done [#B] read and modify the Vault values
   SCHEDULED: <2019-08-02 Fri>
   Looks like some of the scheduling hooks are not present in the Chart (nodeSelector, taints/tolerations, ??)
** done What about a test to make sure ctrlplane is not running a k3s agent/kubelet?
   SCHEDULED: <2019-07-22 Mon>
** done What's the resolution for Consul via Helm as **dedicated** Vault storage?
   DEADLINE: <2019-07-24 Wed> SCHEDULED: <2019-07-22 Mon>
** done [#A] Why are workers not getting an update node-token?
   DEADLINE: <2019-07-22 Mon>
** done [#A] read and modify the Consul values
*** done spread amongst AZs
    DEADLINE: <2019-08-01 Thu>
